rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = Console

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c: %m%n

# Opcional: Você pode silenciar o Spark e o Hadoop individualmente para ficar ainda mais limpo
logger.spark.name = org.apache.spark
logger.spark.level = warn
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn